/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PaqueteTriki;

/**
 *
 * @author MARTHA
 */
public class VentanaInicial extends javax.swing.JFrame {

    private String usuario1;
    private String usuario2;
    
    
    /**
     * Creates new form VentanaInicial
     */
    public VentanaInicial() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        EtiquetaNombre1 = new javax.swing.JLabel();
        EtiquetaNombre2 = new javax.swing.JLabel();
        CajaNombre1 = new javax.swing.JTextField();
        CajaNombre2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BotonGuardar = new javax.swing.JButton();
        EtiquetaMuestra1 = new javax.swing.JLabel();
        EtiquetaMuestra2 = new javax.swing.JLabel();
        BotonComenzar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setEnabled(false);
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("TRES EN RAYA");
        Panel.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 51, -1, -1));

        EtiquetaNombre1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EtiquetaNombre1.setText("Nombre Usuario 1: ");
        Panel.add(EtiquetaNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 132, -1, -1));

        EtiquetaNombre2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EtiquetaNombre2.setText("Nombre Usuario 2:");
        Panel.add(EtiquetaNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 186, -1, -1));

        CajaNombre1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Panel.add(CajaNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 129, 207, -1));

        CajaNombre2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Panel.add(CajaNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 210, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\TresEnRaya\\src\\main\\java\\Imagenes\\Tic_Tac_Toe.gif")); // NOI18N
        Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 220, 200));

        BotonGuardar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BotonGuardar.setText("Guardar");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });
        Panel.add(BotonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        EtiquetaMuestra1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Panel.add(EtiquetaMuestra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        EtiquetaMuestra2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Panel.add(EtiquetaMuestra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        BotonComenzar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        BotonComenzar.setText("Comenzar Juego");
        BotonComenzar.setVisible(false);
        BotonComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonComenzarActionPerformed(evt);
            }
        });
        Panel.add(BotonComenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        // TODO add your handling code here:
        
        usuario1 = CajaNombre1.getText();
        usuario2 = CajaNombre2.getText();
        
        BotonGuardar.setVisible(false);
        EtiquetaMuestra1.setText(usuario1+", Jugara primero su ficha es: X");
        EtiquetaMuestra2.setText(usuario2+", su ficha es: O");
        BotonComenzar.setVisible(true);
        
    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void BotonComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonComenzarActionPerformed
        // TODO add your handling code here:
        
        VentanaPrincipal ventanaP = new VentanaPrincipal(usuario1,usuario2);
        
        ventanaP.setVisible(true);
        
        dispose();
        
    }//GEN-LAST:event_BotonComenzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonComenzar;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JTextField CajaNombre1;
    private javax.swing.JTextField CajaNombre2;
    private javax.swing.JLabel EtiquetaMuestra1;
    private javax.swing.JLabel EtiquetaMuestra2;
    private javax.swing.JLabel EtiquetaNombre1;
    private javax.swing.JLabel EtiquetaNombre2;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
